/**
 * Realistic sample data for Tottenham Hotspur fixtures.
 * Based on the 2024-25 Premier League season for development and testing.
 */

import type {
  Team,
  Venue,
  Fixture,
  StandingsEntry,
  Lineup,
  MatchEvent,
  MatchStatistics,
} from "./provider";

// ---------------------------------------------------------------------------
// Teams
// ---------------------------------------------------------------------------

export const SPURS: Team = {
  id: 6,
  name: "Tottenham Hotspur",
  shortName: "Spurs",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/6/6.png",
  venueId: 214,
};

const TEAMS: Record<number, Team> = {
  6: SPURS,
  1: {
    id: 1,
    name: "Manchester City",
    shortName: "Man City",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/1/1.png",
    venueId: 200,
  },
  14: {
    id: 14,
    name: "Arsenal",
    shortName: "Arsenal",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/14/14.png",
    venueId: 201,
  },
  8: {
    id: 8,
    name: "Liverpool",
    shortName: "Liverpool",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/8/8.png",
    venueId: 202,
  },
  9: {
    id: 9,
    name: "Chelsea",
    shortName: "Chelsea",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/9/9.png",
    venueId: 203,
  },
  25: {
    id: 25,
    name: "Manchester United",
    shortName: "Man Utd",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/25/25.png",
    venueId: 204,
  },
  7: {
    id: 7,
    name: "Aston Villa",
    shortName: "Aston Villa",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/7/7.png",
    venueId: 205,
  },
  10: {
    id: 10,
    name: "Newcastle United",
    shortName: "Newcastle",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/10/10.png",
    venueId: 206,
  },
  12: {
    id: 12,
    name: "Brighton & Hove Albion",
    shortName: "Brighton",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/12/12.png",
    venueId: 207,
  },
  18: {
    id: 18,
    name: "West Ham United",
    shortName: "West Ham",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/18/18.png",
    venueId: 208,
  },
  3: {
    id: 3,
    name: "Brentford",
    shortName: "Brentford",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/3/3.png",
    venueId: 209,
  },
  19: {
    id: 19,
    name: "Wolverhampton Wanderers",
    shortName: "Wolves",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/19/19.png",
    venueId: 210,
  },
  2: {
    id: 2,
    name: "Nottingham Forest",
    shortName: "Nott'm Forest",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/2/2.png",
    venueId: 211,
  },
  4: {
    id: 4,
    name: "Fulham",
    shortName: "Fulham",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/4/4.png",
    venueId: 212,
  },
  21: {
    id: 21,
    name: "Crystal Palace",
    shortName: "Crystal Palace",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/21/21.png",
    venueId: 213,
  },
  26: {
    id: 26,
    name: "Bournemouth",
    shortName: "Bournemouth",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/26/26.png",
    venueId: 215,
  },
  15: {
    id: 15,
    name: "Everton",
    shortName: "Everton",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/15/15.png",
    venueId: 216,
  },
  16: {
    id: 16,
    name: "Leicester City",
    shortName: "Leicester",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/16/16.png",
    venueId: 217,
  },
  22: {
    id: 22,
    name: "Ipswich Town",
    shortName: "Ipswich",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/22/22.png",
    venueId: 218,
  },
  23: {
    id: 23,
    name: "Southampton",
    shortName: "Southampton",
    logo: "https://cdn.sportmonks.com/images/soccer/teams/23/23.png",
    venueId: 219,
  },
};

// ---------------------------------------------------------------------------
// Venues
// ---------------------------------------------------------------------------

const TOTTENHAM_STADIUM: Venue = {
  id: 214,
  name: "Tottenham Hotspur Stadium",
  city: "London",
  capacity: 62850,
  image:
    "https://cdn.sportmonks.com/images/soccer/venues/214.png",
  latitude: 51.6042,
  longitude: -0.0662,
};

const VENUES: Record<number, Venue> = {
  214: TOTTENHAM_STADIUM,
  200: {
    id: 200,
    name: "Etihad Stadium",
    city: "Manchester",
    capacity: 53400,
    latitude: 53.4831,
    longitude: -2.2004,
  },
  201: {
    id: 201,
    name: "Emirates Stadium",
    city: "London",
    capacity: 60704,
    latitude: 51.5549,
    longitude: -0.1084,
  },
  202: {
    id: 202,
    name: "Anfield",
    city: "Liverpool",
    capacity: 61276,
    latitude: 53.4308,
    longitude: -2.9609,
  },
  203: {
    id: 203,
    name: "Stamford Bridge",
    city: "London",
    capacity: 40343,
    latitude: 51.4817,
    longitude: -0.191,
  },
  204: {
    id: 204,
    name: "Old Trafford",
    city: "Manchester",
    capacity: 74310,
    latitude: 53.4631,
    longitude: -2.2913,
  },
  205: {
    id: 205,
    name: "Villa Park",
    city: "Birmingham",
    capacity: 42788,
    latitude: 52.5092,
    longitude: -1.8847,
  },
  206: {
    id: 206,
    name: "St James' Park",
    city: "Newcastle",
    capacity: 52305,
    latitude: 54.9756,
    longitude: -1.6217,
  },
  207: {
    id: 207,
    name: "Amex Stadium",
    city: "Brighton",
    capacity: 31876,
    latitude: 50.8616,
    longitude: -0.0837,
  },
  208: {
    id: 208,
    name: "London Stadium",
    city: "London",
    capacity: 62500,
    latitude: 51.5387,
    longitude: -0.0166,
  },
};

// ---------------------------------------------------------------------------
// Fixtures (2024-25 season)
// ---------------------------------------------------------------------------

const PL_LEAGUE_ID = 8;
const PL_LEAGUE_NAME = "Premier League";
const SEASON_ID = 23614;

export const SAMPLE_FIXTURES: Fixture[] = [
  // Past results
  {
    id: 100001,
    homeTeam: TEAMS[16],
    awayTeam: SPURS,
    venue: VENUES[217] ?? null,
    date: "2024-08-19T19:00:00Z",
    status: "finished",
    score: { home: 1, away: 1 },
    minute: null,
    round: "Matchweek 1",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100002,
    homeTeam: SPURS,
    awayTeam: TEAMS[15],
    venue: TOTTENHAM_STADIUM,
    date: "2024-08-24T14:00:00Z",
    status: "finished",
    score: { home: 4, away: 0 },
    minute: null,
    round: "Matchweek 2",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100003,
    homeTeam: TEAMS[10],
    awayTeam: SPURS,
    venue: VENUES[206] ?? null,
    date: "2024-09-01T13:00:00Z",
    status: "finished",
    score: { home: 2, away: 1 },
    minute: null,
    round: "Matchweek 3",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100004,
    homeTeam: SPURS,
    awayTeam: TEAMS[14],
    venue: TOTTENHAM_STADIUM,
    date: "2024-09-15T15:30:00Z",
    status: "finished",
    score: { home: 0, away: 1 },
    minute: null,
    round: "Matchweek 4",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100005,
    homeTeam: SPURS,
    awayTeam: TEAMS[3],
    venue: TOTTENHAM_STADIUM,
    date: "2024-09-21T14:00:00Z",
    status: "finished",
    score: { home: 3, away: 1 },
    minute: null,
    round: "Matchweek 5",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100006,
    homeTeam: TEAMS[25],
    awayTeam: SPURS,
    venue: VENUES[204] ?? null,
    date: "2024-09-29T15:30:00Z",
    status: "finished",
    score: { home: 0, away: 3 },
    minute: null,
    round: "Matchweek 6",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100007,
    homeTeam: SPURS,
    awayTeam: TEAMS[18],
    venue: TOTTENHAM_STADIUM,
    date: "2024-10-19T14:00:00Z",
    status: "finished",
    score: { home: 4, away: 1 },
    minute: null,
    round: "Matchweek 8",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100008,
    homeTeam: TEAMS[21],
    awayTeam: SPURS,
    venue: VENUES[213] ?? null,
    date: "2024-10-27T13:00:00Z",
    status: "finished",
    score: { home: 1, away: 0 },
    minute: null,
    round: "Matchweek 9",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100009,
    homeTeam: SPURS,
    awayTeam: TEAMS[7],
    venue: TOTTENHAM_STADIUM,
    date: "2024-11-03T16:30:00Z",
    status: "finished",
    score: { home: 4, away: 1 },
    minute: null,
    round: "Matchweek 10",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100010,
    homeTeam: SPURS,
    awayTeam: TEAMS[22],
    venue: TOTTENHAM_STADIUM,
    date: "2024-11-10T14:00:00Z",
    status: "finished",
    score: { home: 4, away: 1 },
    minute: null,
    round: "Matchweek 11",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100011,
    homeTeam: TEAMS[1],
    awayTeam: SPURS,
    venue: VENUES[200] ?? null,
    date: "2024-11-23T17:30:00Z",
    status: "finished",
    score: { home: 0, away: 4 },
    minute: null,
    round: "Matchweek 12",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100012,
    homeTeam: SPURS,
    awayTeam: TEAMS[4],
    venue: TOTTENHAM_STADIUM,
    date: "2024-12-01T14:00:00Z",
    status: "finished",
    score: { home: 1, away: 1 },
    minute: null,
    round: "Matchweek 13",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100013,
    homeTeam: SPURS,
    awayTeam: TEAMS[9],
    venue: TOTTENHAM_STADIUM,
    date: "2024-12-08T16:30:00Z",
    status: "finished",
    score: { home: 3, away: 4 },
    minute: null,
    round: "Matchweek 15",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100014,
    homeTeam: TEAMS[23],
    awayTeam: SPURS,
    venue: VENUES[219] ?? null,
    date: "2024-12-15T14:00:00Z",
    status: "finished",
    score: { home: 0, away: 5 },
    minute: null,
    round: "Matchweek 16",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100015,
    homeTeam: SPURS,
    awayTeam: TEAMS[8],
    venue: TOTTENHAM_STADIUM,
    date: "2024-12-22T16:30:00Z",
    status: "finished",
    score: { home: 3, away: 6 },
    minute: null,
    round: "Matchweek 17",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100016,
    homeTeam: SPURS,
    awayTeam: TEAMS[19],
    venue: TOTTENHAM_STADIUM,
    date: "2024-12-29T14:00:00Z",
    status: "finished",
    score: { home: 2, away: 2 },
    minute: null,
    round: "Matchweek 19",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100017,
    homeTeam: TEAMS[2],
    awayTeam: SPURS,
    venue: VENUES[211] ?? null,
    date: "2025-01-26T14:00:00Z",
    status: "finished",
    score: { home: 1, away: 0 },
    minute: null,
    round: "Matchweek 22",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100018,
    homeTeam: TEAMS[8],
    awayTeam: SPURS,
    venue: VENUES[202] ?? null,
    date: "2025-02-05T20:00:00Z",
    status: "finished",
    score: { home: 3, away: 0 },
    minute: null,
    round: "Matchweek 24",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100019,
    homeTeam: SPURS,
    awayTeam: TEAMS[25],
    venue: TOTTENHAM_STADIUM,
    date: "2025-02-16T14:00:00Z",
    status: "finished",
    score: { home: 3, away: 0 },
    minute: null,
    round: "Matchweek 25",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100020,
    homeTeam: TEAMS[22],
    awayTeam: SPURS,
    venue: VENUES[218] ?? null,
    date: "2025-02-22T15:00:00Z",
    status: "finished",
    score: { home: 0, away: 2 },
    minute: null,
    round: "Matchweek 26",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100021,
    homeTeam: SPURS,
    awayTeam: TEAMS[26],
    venue: TOTTENHAM_STADIUM,
    date: "2025-03-08T15:00:00Z",
    status: "finished",
    score: { home: 3, away: 2 },
    minute: null,
    round: "Matchweek 28",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100022,
    homeTeam: TEAMS[14],
    awayTeam: SPURS,
    venue: VENUES[201] ?? null,
    date: "2025-03-16T16:30:00Z",
    status: "finished",
    score: { home: 2, away: 2 },
    minute: null,
    round: "Matchweek 29",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100023,
    homeTeam: SPURS,
    awayTeam: TEAMS[10],
    venue: TOTTENHAM_STADIUM,
    date: "2025-04-05T14:00:00Z",
    status: "finished",
    score: { home: 1, away: 2 },
    minute: null,
    round: "Matchweek 31",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100024,
    homeTeam: SPURS,
    awayTeam: TEAMS[2],
    venue: TOTTENHAM_STADIUM,
    date: "2025-04-13T14:00:00Z",
    status: "finished",
    score: { home: 1, away: 0 },
    minute: null,
    round: "Matchweek 33",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100025,
    homeTeam: SPURS,
    awayTeam: TEAMS[1],
    venue: TOTTENHAM_STADIUM,
    date: "2025-05-04T16:30:00Z",
    status: "finished",
    score: { home: 1, away: 0 },
    minute: null,
    round: "Matchweek 35",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100026,
    homeTeam: TEAMS[12],
    awayTeam: SPURS,
    venue: VENUES[207] ?? null,
    date: "2025-05-10T14:00:00Z",
    status: "finished",
    score: { home: 2, away: 1 },
    minute: null,
    round: "Matchweek 36",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100027,
    homeTeam: SPURS,
    awayTeam: TEAMS[23],
    venue: TOTTENHAM_STADIUM,
    date: "2025-05-18T15:00:00Z",
    status: "finished",
    score: { home: 2, away: 0 },
    minute: null,
    round: "Matchweek 37",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },
  {
    id: 100028,
    homeTeam: TEAMS[9],
    awayTeam: SPURS,
    venue: VENUES[203] ?? null,
    date: "2025-05-25T16:00:00Z",
    status: "finished",
    score: { home: 1, away: 3 },
    minute: null,
    round: "Matchweek 38",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID,
  },

  // Upcoming 2025-26 fixtures (scheduled)
  {
    id: 200001,
    homeTeam: SPURS,
    awayTeam: TEAMS[15],
    venue: TOTTENHAM_STADIUM,
    date: "2025-09-27T14:00:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 6",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200002,
    homeTeam: TEAMS[1],
    awayTeam: SPURS,
    venue: VENUES[200] ?? null,
    date: "2025-10-04T16:30:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 7",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200003,
    homeTeam: SPURS,
    awayTeam: TEAMS[18],
    venue: TOTTENHAM_STADIUM,
    date: "2025-10-18T14:00:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 8",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200004,
    homeTeam: TEAMS[8],
    awayTeam: SPURS,
    venue: VENUES[202] ?? null,
    date: "2025-10-25T12:30:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 9",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200005,
    homeTeam: SPURS,
    awayTeam: TEAMS[14],
    venue: TOTTENHAM_STADIUM,
    date: "2025-11-08T17:30:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 11",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200006,
    homeTeam: TEAMS[9],
    awayTeam: SPURS,
    venue: VENUES[203] ?? null,
    date: "2025-11-23T16:30:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 12",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200007,
    homeTeam: SPURS,
    awayTeam: TEAMS[25],
    venue: TOTTENHAM_STADIUM,
    date: "2025-12-06T15:00:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 15",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
  {
    id: 200008,
    homeTeam: SPURS,
    awayTeam: TEAMS[12],
    venue: TOTTENHAM_STADIUM,
    date: "2025-12-21T15:00:00Z",
    status: "scheduled",
    score: null,
    minute: null,
    round: "Matchweek 17",
    leagueId: PL_LEAGUE_ID,
    leagueName: PL_LEAGUE_NAME,
    seasonId: SEASON_ID + 1,
  },
];

// ---------------------------------------------------------------------------
// Standings (end of 2024-25 season snapshot)
// ---------------------------------------------------------------------------

export const SAMPLE_STANDINGS: StandingsEntry[] = [
  {
    position: 1,
    team: TEAMS[8],
    played: 38,
    won: 28,
    drawn: 7,
    lost: 3,
    goalsFor: 86,
    goalsAgainst: 29,
    goalDifference: 57,
    points: 91,
    form: ["W", "W", "W", "D", "W"],
  },
  {
    position: 2,
    team: TEAMS[14],
    played: 38,
    won: 24,
    drawn: 8,
    lost: 6,
    goalsFor: 77,
    goalsAgainst: 33,
    goalDifference: 44,
    points: 80,
    form: ["W", "D", "W", "W", "D"],
  },
  {
    position: 3,
    team: TEAMS[2],
    played: 38,
    won: 22,
    drawn: 7,
    lost: 9,
    goalsFor: 62,
    goalsAgainst: 38,
    goalDifference: 24,
    points: 73,
    form: ["L", "W", "W", "D", "W"],
  },
  {
    position: 4,
    team: TEAMS[9],
    played: 38,
    won: 21,
    drawn: 8,
    lost: 9,
    goalsFor: 72,
    goalsAgainst: 45,
    goalDifference: 27,
    points: 71,
    form: ["W", "L", "W", "W", "W"],
  },
  {
    position: 5,
    team: TEAMS[7],
    played: 38,
    won: 19,
    drawn: 9,
    lost: 10,
    goalsFor: 60,
    goalsAgainst: 51,
    goalDifference: 9,
    points: 66,
    form: ["D", "W", "L", "W", "D"],
  },
  {
    position: 6,
    team: TEAMS[26],
    played: 38,
    won: 19,
    drawn: 7,
    lost: 12,
    goalsFor: 59,
    goalsAgainst: 47,
    goalDifference: 12,
    points: 64,
    form: ["W", "W", "L", "W", "L"],
  },
  {
    position: 7,
    team: TEAMS[1],
    played: 38,
    won: 18,
    drawn: 10,
    lost: 10,
    goalsFor: 68,
    goalsAgainst: 48,
    goalDifference: 20,
    points: 64,
    form: ["D", "L", "W", "D", "W"],
  },
  {
    position: 8,
    team: TEAMS[10],
    played: 38,
    won: 18,
    drawn: 6,
    lost: 14,
    goalsFor: 55,
    goalsAgainst: 48,
    goalDifference: 7,
    points: 60,
    form: ["W", "W", "L", "L", "W"],
  },
  {
    position: 9,
    team: TEAMS[4],
    played: 38,
    won: 15,
    drawn: 12,
    lost: 11,
    goalsFor: 53,
    goalsAgainst: 49,
    goalDifference: 4,
    points: 57,
    form: ["D", "D", "W", "L", "W"],
  },
  {
    position: 10,
    team: TEAMS[12],
    played: 38,
    won: 14,
    drawn: 13,
    lost: 11,
    goalsFor: 58,
    goalsAgainst: 54,
    goalDifference: 4,
    points: 55,
    form: ["D", "W", "D", "L", "W"],
  },
  {
    position: 11,
    team: SPURS,
    played: 38,
    won: 15,
    drawn: 7,
    lost: 16,
    goalsFor: 69,
    goalsAgainst: 63,
    goalDifference: 6,
    points: 52,
    form: ["W", "L", "W", "W", "L"],
  },
  {
    position: 12,
    team: TEAMS[3],
    played: 38,
    won: 13,
    drawn: 8,
    lost: 17,
    goalsFor: 54,
    goalsAgainst: 57,
    goalDifference: -3,
    points: 47,
    form: ["L", "W", "D", "L", "W"],
  },
  {
    position: 13,
    team: TEAMS[18],
    played: 38,
    won: 13,
    drawn: 7,
    lost: 18,
    goalsFor: 47,
    goalsAgainst: 59,
    goalDifference: -12,
    points: 46,
    form: ["L", "L", "W", "D", "L"],
  },
  {
    position: 14,
    team: TEAMS[25],
    played: 38,
    won: 12,
    drawn: 10,
    lost: 16,
    goalsFor: 42,
    goalsAgainst: 55,
    goalDifference: -13,
    points: 46,
    form: ["D", "L", "L", "W", "D"],
  },
  {
    position: 15,
    team: TEAMS[21],
    played: 38,
    won: 11,
    drawn: 10,
    lost: 17,
    goalsFor: 39,
    goalsAgainst: 52,
    goalDifference: -13,
    points: 43,
    form: ["L", "D", "W", "L", "D"],
  },
  {
    position: 16,
    team: TEAMS[15],
    played: 38,
    won: 10,
    drawn: 9,
    lost: 19,
    goalsFor: 34,
    goalsAgainst: 51,
    goalDifference: -17,
    points: 39,
    form: ["L", "D", "L", "W", "L"],
  },
  {
    position: 17,
    team: TEAMS[19],
    played: 38,
    won: 10,
    drawn: 8,
    lost: 20,
    goalsFor: 44,
    goalsAgainst: 65,
    goalDifference: -21,
    points: 38,
    form: ["L", "L", "D", "L", "W"],
  },
  {
    position: 18,
    team: TEAMS[16],
    played: 38,
    won: 7,
    drawn: 10,
    lost: 21,
    goalsFor: 32,
    goalsAgainst: 63,
    goalDifference: -31,
    points: 31,
    form: ["L", "L", "D", "L", "L"],
  },
  {
    position: 19,
    team: TEAMS[22],
    played: 38,
    won: 6,
    drawn: 10,
    lost: 22,
    goalsFor: 28,
    goalsAgainst: 68,
    goalDifference: -40,
    points: 28,
    form: ["L", "L", "L", "D", "L"],
  },
  {
    position: 20,
    team: TEAMS[23],
    played: 38,
    won: 4,
    drawn: 7,
    lost: 27,
    goalsFor: 22,
    goalsAgainst: 75,
    goalDifference: -53,
    points: 19,
    form: ["L", "L", "L", "L", "D"],
  },
];

// ---------------------------------------------------------------------------
// Sample lineup (Spurs vs Everton, Matchweek 2)
// ---------------------------------------------------------------------------

export const SAMPLE_LINEUP: Lineup = {
  formation: "4-3-3",
  startingXI: [
    { id: 201, name: "Guglielmo Vicario", number: 13, position: "GK", isCaptain: false },
    { id: 202, name: "Pedro Porro", number: 23, position: "RB", isCaptain: false },
    { id: 203, name: "Cristian Romero", number: 17, position: "CB", isCaptain: true },
    { id: 204, name: "Micky van de Ven", number: 37, position: "CB", isCaptain: false },
    { id: 205, name: "Destiny Udogie", number: 13, position: "LB", isCaptain: false },
    { id: 206, name: "Yves Bissouma", number: 38, position: "CM", isCaptain: false },
    { id: 207, name: "Pape Matar Sarr", number: 29, position: "CM", isCaptain: false },
    { id: 208, name: "James Maddison", number: 10, position: "AM", isCaptain: false },
    { id: 209, name: "Dejan Kulusevski", number: 21, position: "RW", isCaptain: false },
    { id: 210, name: "Dominic Solanke", number: 19, position: "ST", isCaptain: false },
    { id: 211, name: "Son Heung-min", number: 7, position: "LW", isCaptain: false },
  ],
  substitutes: [
    { id: 212, name: "Fraser Forster", number: 20, position: "GK", isCaptain: false },
    { id: 213, name: "Radu Dragusin", number: 6, position: "CB", isCaptain: false },
    { id: 214, name: "Ben Davies", number: 33, position: "CB", isCaptain: false },
    { id: 215, name: "Rodrigo Bentancur", number: 30, position: "CM", isCaptain: false },
    { id: 216, name: "Brennan Johnson", number: 22, position: "RW", isCaptain: false },
    { id: 217, name: "Timo Werner", number: 16, position: "LW", isCaptain: false },
    { id: 218, name: "Richarlison", number: 9, position: "ST", isCaptain: false },
  ],
  coach: "Ange Postecoglou",
};

// ---------------------------------------------------------------------------
// Sample match events (Spurs 4-0 Everton)
// ---------------------------------------------------------------------------

export const SAMPLE_EVENTS: MatchEvent[] = [
  {
    id: 1001,
    minute: 14,
    extraMinute: null,
    type: "goal",
    teamId: 6,
    playerName: "Son Heung-min",
    relatedPlayerName: "James Maddison",
    description: "Left-footed shot from the centre of the box.",
  },
  {
    id: 1002,
    minute: 25,
    extraMinute: null,
    type: "yellow_card",
    teamId: 15,
    playerName: "James Tarkowski",
    relatedPlayerName: null,
    description: "Foul on Dejan Kulusevski.",
  },
  {
    id: 1003,
    minute: 29,
    extraMinute: null,
    type: "goal",
    teamId: 6,
    playerName: "Cristian Romero",
    relatedPlayerName: "James Maddison",
    description: "Header from a corner kick.",
  },
  {
    id: 1004,
    minute: 52,
    extraMinute: null,
    type: "goal",
    teamId: 6,
    playerName: "Dejan Kulusevski",
    relatedPlayerName: "Son Heung-min",
    description: "Right-footed shot from outside the box to the bottom left corner.",
  },
  {
    id: 1005,
    minute: 62,
    extraMinute: null,
    type: "substitution",
    teamId: 6,
    playerName: "Brennan Johnson",
    relatedPlayerName: "Dejan Kulusevski",
    description: null,
  },
  {
    id: 1006,
    minute: 71,
    extraMinute: null,
    type: "goal",
    teamId: 6,
    playerName: "Dominic Solanke",
    relatedPlayerName: "Pedro Porro",
    description: "Right-footed shot from the centre of the box.",
  },
  {
    id: 1007,
    minute: 78,
    extraMinute: null,
    type: "substitution",
    teamId: 6,
    playerName: "Richarlison",
    relatedPlayerName: "Dominic Solanke",
    description: null,
  },
  {
    id: 1008,
    minute: 78,
    extraMinute: null,
    type: "substitution",
    teamId: 6,
    playerName: "Rodrigo Bentancur",
    relatedPlayerName: "Pape Matar Sarr",
    description: null,
  },
];

// ---------------------------------------------------------------------------
// Sample match statistics (Spurs 4-0 Everton)
// ---------------------------------------------------------------------------

export const SAMPLE_STATISTICS: MatchStatistics = {
  fixtureId: 100002,
  home: {
    possession: 62,
    shots: 18,
    shotsOnTarget: 9,
    corners: 7,
    fouls: 8,
    offsides: 2,
    yellowCards: 0,
    redCards: 0,
    passes: 547,
    passAccuracy: 88,
  },
  away: {
    possession: 38,
    shots: 5,
    shotsOnTarget: 1,
    corners: 2,
    fouls: 14,
    offsides: 1,
    yellowCards: 2,
    redCards: 0,
    passes: 338,
    passAccuracy: 76,
  },
};

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

export function getSampleTeam(teamId: number): Team | null {
  return TEAMS[teamId] ?? null;
}

export function getSampleVenue(venueId: number): Venue | null {
  return VENUES[venueId] ?? null;
}
